// Maps first 3 digits of US zip codes to USDA hardiness zones
// This is approximate - microclimates exist. But it's good enough for filtering.
// Source: USDA 2023 Plant Hardiness Zone Map, aggregated by zip3 prefix

const ZIP3_TO_ZONE: Record<string, { zone: number; half: string; region: string }> = {
  // Northeast
  "010": { zone: 6, half: "a", region: "Springfield, MA" },
  "011": { zone: 6, half: "a", region: "Springfield, MA" },
  "012": { zone: 5, half: "b", region: "Pittsfield, MA" },
  "013": { zone: 6, half: "a", region: "Greenfield, MA" },
  "014": { zone: 6, half: "a", region: "Fitchburg, MA" },
  "015": { zone: 6, half: "a", region: "Worcester, MA" },
  "016": { zone: 6, half: "a", region: "Worcester, MA" },
  "017": { zone: 6, half: "b", region: "Framingham, MA" },
  "018": { zone: 6, half: "b", region: "Woburn, MA" },
  "019": { zone: 6, half: "b", region: "Lynn, MA" },
  "020": { zone: 7, half: "a", region: "Brockton, MA" },
  "021": { zone: 6, half: "b", region: "Boston, MA" },
  "022": { zone: 6, half: "b", region: "Boston, MA" },
  "023": { zone: 6, half: "b", region: "Brockton, MA" },
  "024": { zone: 6, half: "b", region: "Lexington, MA" },
  "025": { zone: 7, half: "a", region: "Cape Cod, MA" },
  "026": { zone: 7, half: "a", region: "Cape Cod, MA" },
  "027": { zone: 7, half: "a", region: "New Bedford, MA" },
  "028": { zone: 6, half: "b", region: "Providence, RI" },
  "029": { zone: 6, half: "b", region: "Providence, RI" },
  "030": { zone: 5, half: "b", region: "Manchester, NH" },
  "031": { zone: 5, half: "b", region: "Manchester, NH" },
  "032": { zone: 5, half: "a", region: "Concord, NH" },
  "033": { zone: 5, half: "a", region: "Concord, NH" },
  "034": { zone: 5, half: "a", region: "Keene, NH" },
  "035": { zone: 4, half: "b", region: "Littleton, NH" },
  "036": { zone: 4, half: "b", region: "Berlin, NH" },
  "037": { zone: 5, half: "a", region: "Claremont, NH" },
  "038": { zone: 5, half: "b", region: "Portsmouth, NH" },
  "039": { zone: 5, half: "b", region: "Portsmouth, NH" },
  "040": { zone: 5, half: "b", region: "Portland, ME" },
  "041": { zone: 5, half: "b", region: "Portland, ME" },
  "042": { zone: 5, half: "a", region: "Auburn, ME" },
  "043": { zone: 5, half: "a", region: "Augusta, ME" },
  "044": { zone: 5, half: "a", region: "Bangor, ME" },
  "045": { zone: 4, half: "b", region: "Bath, ME" },
  "046": { zone: 4, half: "a", region: "Machias, ME" },
  "047": { zone: 4, half: "a", region: "Houlton, ME" },
  "048": { zone: 4, half: "a", region: "Rockland, ME" },
  "049": { zone: 5, half: "a", region: "Waterville, ME" },
  "050": { zone: 5, half: "a", region: "White River Jct, VT" },
  "051": { zone: 4, half: "b", region: "Bellows Falls, VT" },
  "052": { zone: 4, half: "b", region: "Bennington, VT" },
  "053": { zone: 4, half: "b", region: "Brattleboro, VT" },
  "054": { zone: 4, half: "b", region: "Burlington, VT" },
  "055": { zone: 4, half: "b", region: "Montpelier, VT" },
  "056": { zone: 4, half: "a", region: "Montpelier, VT" },
  "057": { zone: 4, half: "b", region: "Rutland, VT" },
  "058": { zone: 4, half: "a", region: "St. Johnsbury, VT" },
  "059": { zone: 4, half: "b", region: "Burlington, VT" },
  "060": { zone: 6, half: "b", region: "Hartford, CT" },
  "061": { zone: 6, half: "b", region: "Hartford, CT" },
  "062": { zone: 6, half: "b", region: "Willimantic, CT" },
  "063": { zone: 6, half: "b", region: "New London, CT" },
  "064": { zone: 6, half: "b", region: "New Haven, CT" },
  "065": { zone: 7, half: "a", region: "New Haven, CT" },
  "066": { zone: 7, half: "a", region: "Bridgeport, CT" },
  "067": { zone: 6, half: "b", region: "Waterbury, CT" },
  "068": { zone: 6, half: "b", region: "Stamford, CT" },
  "069": { zone: 7, half: "a", region: "Stamford, CT" },
  // New York
  "100": { zone: 7, half: "b", region: "New York, NY" },
  "101": { zone: 7, half: "b", region: "New York, NY" },
  "102": { zone: 7, half: "b", region: "New York, NY" },
  "103": { zone: 7, half: "b", region: "Staten Island, NY" },
  "104": { zone: 7, half: "b", region: "Bronx, NY" },
  "105": { zone: 7, half: "a", region: "Westchester, NY" },
  "106": { zone: 7, half: "a", region: "White Plains, NY" },
  "107": { zone: 7, half: "a", region: "Yonkers, NY" },
  "108": { zone: 7, half: "a", region: "New Rochelle, NY" },
  "109": { zone: 6, half: "b", region: "Suffern, NY" },
  "110": { zone: 7, half: "b", region: "Queens, NY" },
  "111": { zone: 7, half: "b", region: "Long Island City, NY" },
  "112": { zone: 7, half: "b", region: "Brooklyn, NY" },
  "113": { zone: 7, half: "b", region: "Flushing, NY" },
  "114": { zone: 7, half: "b", region: "Jamaica, NY" },
  "115": { zone: 7, half: "a", region: "Mineola, NY" },
  "116": { zone: 7, half: "a", region: "Long Island, NY" },
  "117": { zone: 7, half: "a", region: "Hicksville, NY" },
  "118": { zone: 7, half: "a", region: "Huntington, NY" },
  "119": { zone: 7, half: "a", region: "Riverhead, NY" },
  "120": { zone: 6, half: "a", region: "Albany, NY" },
  "121": { zone: 5, half: "b", region: "Albany, NY" },
  "122": { zone: 5, half: "b", region: "Albany, NY" },
  "123": { zone: 5, half: "b", region: "Schenectady, NY" },
  "124": { zone: 6, half: "a", region: "Kingston, NY" },
  "125": { zone: 6, half: "a", region: "Poughkeepsie, NY" },
  "126": { zone: 6, half: "a", region: "Poughkeepsie, NY" },
  "127": { zone: 6, half: "a", region: "Middletown, NY" },
  "128": { zone: 5, half: "b", region: "Glens Falls, NY" },
  "129": { zone: 5, half: "a", region: "Plattsburgh, NY" },
  "130": { zone: 5, half: "b", region: "Syracuse, NY" },
  "131": { zone: 5, half: "b", region: "Syracuse, NY" },
  "132": { zone: 5, half: "b", region: "Syracuse, NY" },
  "133": { zone: 5, half: "a", region: "Utica, NY" },
  "134": { zone: 5, half: "a", region: "Utica, NY" },
  "135": { zone: 5, half: "a", region: "Utica, NY" },
  "136": { zone: 5, half: "a", region: "Watertown, NY" },
  "137": { zone: 5, half: "b", region: "Binghamton, NY" },
  "138": { zone: 5, half: "b", region: "Binghamton, NY" },
  "139": { zone: 5, half: "b", region: "Binghamton, NY" },
  "140": { zone: 6, half: "a", region: "Buffalo, NY" },
  "141": { zone: 6, half: "a", region: "Buffalo, NY" },
  "142": { zone: 6, half: "a", region: "Buffalo, NY" },
  "143": { zone: 6, half: "a", region: "Niagara Falls, NY" },
  "144": { zone: 6, half: "a", region: "Rochester, NY" },
  "145": { zone: 6, half: "a", region: "Rochester, NY" },
  "146": { zone: 6, half: "a", region: "Rochester, NY" },
  "147": { zone: 5, half: "b", region: "Jamestown, NY" },
  "148": { zone: 5, half: "b", region: "Elmira, NY" },
  "149": { zone: 5, half: "b", region: "Elmira, NY" },
  // New Jersey
  "070": { zone: 7, half: "a", region: "Newark, NJ" },
  "071": { zone: 7, half: "a", region: "Newark, NJ" },
  "072": { zone: 7, half: "a", region: "Elizabeth, NJ" },
  "073": { zone: 7, half: "a", region: "Jersey City, NJ" },
  "074": { zone: 6, half: "b", region: "Paterson, NJ" },
  "075": { zone: 6, half: "b", region: "Paterson, NJ" },
  "076": { zone: 7, half: "a", region: "Hackensack, NJ" },
  "077": { zone: 7, half: "a", region: "Red Bank, NJ" },
  "078": { zone: 7, half: "a", region: "Dover, NJ" },
  "079": { zone: 6, half: "b", region: "Summit, NJ" },
  "080": { zone: 7, half: "a", region: "South Jersey" },
  "081": { zone: 7, half: "a", region: "Camden, NJ" },
  "082": { zone: 7, half: "a", region: "South Jersey" },
  "083": { zone: 7, half: "a", region: "Atlantic City, NJ" },
  "084": { zone: 7, half: "a", region: "Atlantic City, NJ" },
  "085": { zone: 7, half: "a", region: "Trenton, NJ" },
  "086": { zone: 7, half: "a", region: "Trenton, NJ" },
  "087": { zone: 7, half: "a", region: "Lakewood, NJ" },
  "088": { zone: 7, half: "a", region: "New Brunswick, NJ" },
  "089": { zone: 7, half: "a", region: "New Brunswick, NJ" },
  // Pennsylvania
  "150": { zone: 6, half: "b", region: "Pittsburgh, PA" },
  "151": { zone: 6, half: "b", region: "Pittsburgh, PA" },
  "152": { zone: 6, half: "b", region: "Pittsburgh, PA" },
  "153": { zone: 6, half: "a", region: "Washington, PA" },
  "154": { zone: 6, half: "a", region: "Uniontown, PA" },
  "155": { zone: 6, half: "a", region: "Johnstown, PA" },
  "156": { zone: 6, half: "a", region: "Greensburg, PA" },
  "157": { zone: 6, half: "a", region: "Indiana, PA" },
  "158": { zone: 5, half: "b", region: "DuBois, PA" },
  "159": { zone: 5, half: "b", region: "Johnstown, PA" },
  "160": { zone: 6, half: "a", region: "Butler, PA" },
  "161": { zone: 5, half: "b", region: "New Castle, PA" },
  "162": { zone: 6, half: "a", region: "Kittanning, PA" },
  "163": { zone: 5, half: "b", region: "Oil City, PA" },
  "164": { zone: 6, half: "a", region: "Erie, PA" },
  "165": { zone: 6, half: "a", region: "Erie, PA" },
  "166": { zone: 5, half: "b", region: "Altoona, PA" },
  "167": { zone: 5, half: "b", region: "Bradford, PA" },
  "168": { zone: 6, half: "a", region: "State College, PA" },
  "169": { zone: 6, half: "a", region: "Wellsboro, PA" },
  "170": { zone: 6, half: "b", region: "Harrisburg, PA" },
  "171": { zone: 6, half: "b", region: "Harrisburg, PA" },
  "172": { zone: 6, half: "b", region: "Chambersburg, PA" },
  "173": { zone: 6, half: "b", region: "York, PA" },
  "174": { zone: 6, half: "b", region: "York, PA" },
  "175": { zone: 6, half: "b", region: "Lancaster, PA" },
  "176": { zone: 6, half: "b", region: "Lancaster, PA" },
  "177": { zone: 6, half: "b", region: "Williamsport, PA" },
  "178": { zone: 6, half: "a", region: "Sunbury, PA" },
  "179": { zone: 6, half: "b", region: "Pottsville, PA" },
  "180": { zone: 6, half: "b", region: "Lehigh Valley, PA" },
  "181": { zone: 6, half: "b", region: "Allentown, PA" },
  "182": { zone: 6, half: "a", region: "Hazleton, PA" },
  "183": { zone: 6, half: "a", region: "Stroudsburg, PA" },
  "184": { zone: 6, half: "a", region: "Scranton, PA" },
  "185": { zone: 6, half: "a", region: "Scranton, PA" },
  "186": { zone: 6, half: "a", region: "Wilkes-Barre, PA" },
  "187": { zone: 6, half: "a", region: "Wilkes-Barre, PA" },
  "188": { zone: 6, half: "a", region: "Montrose, PA" },
  "189": { zone: 6, half: "b", region: "Doylestown, PA" },
  "190": { zone: 7, half: "a", region: "Philadelphia, PA" },
  "191": { zone: 7, half: "a", region: "Philadelphia, PA" },
  "192": { zone: 7, half: "a", region: "Philadelphia, PA" },
  "193": { zone: 7, half: "a", region: "Southeastern PA" },
  "194": { zone: 7, half: "a", region: "Norristown, PA" },
  "195": { zone: 6, half: "b", region: "Reading, PA" },
  "196": { zone: 6, half: "b", region: "Reading, PA" },
  // DC/Maryland/Virginia
  "200": { zone: 7, half: "b", region: "Washington, DC" },
  "201": { zone: 7, half: "a", region: "Dulles, VA" },
  "202": { zone: 7, half: "b", region: "Washington, DC" },
  "203": { zone: 7, half: "b", region: "Washington, DC" },
  "204": { zone: 7, half: "a", region: "Washington, DC" },
  "205": { zone: 7, half: "b", region: "Washington, DC" },
  "206": { zone: 7, half: "a", region: "Southern MD" },
  "207": { zone: 7, half: "a", region: "Southern MD" },
  "208": { zone: 7, half: "a", region: "Suburban MD" },
  "209": { zone: 7, half: "a", region: "Silver Spring, MD" },
  "210": { zone: 7, half: "a", region: "Baltimore, MD" },
  "211": { zone: 7, half: "a", region: "Baltimore, MD" },
  "212": { zone: 7, half: "a", region: "Baltimore, MD" },
  "214": { zone: 7, half: "a", region: "Annapolis, MD" },
  "215": { zone: 7, half: "a", region: "Cumberland, MD" },
  "216": { zone: 6, half: "b", region: "Easton, MD" },
  "217": { zone: 7, half: "a", region: "Frederick, MD" },
  "218": { zone: 7, half: "a", region: "Salisbury, MD" },
  "219": { zone: 7, half: "a", region: "Elkton, MD" },
  "220": { zone: 7, half: "a", region: "Northern VA" },
  "221": { zone: 7, half: "a", region: "Fairfax, VA" },
  "222": { zone: 7, half: "a", region: "Arlington, VA" },
  "223": { zone: 7, half: "a", region: "Alexandria, VA" },
  "224": { zone: 7, half: "a", region: "Fredericksburg, VA" },
  "225": { zone: 7, half: "a", region: "Fredericksburg, VA" },
  "226": { zone: 7, half: "a", region: "Winchester, VA" },
  "227": { zone: 7, half: "a", region: "Culpeper, VA" },
  "228": { zone: 7, half: "a", region: "Harrisonburg, VA" },
  "229": { zone: 7, half: "a", region: "Charlottesville, VA" },
  "230": { zone: 7, half: "b", region: "Richmond, VA" },
  "231": { zone: 7, half: "b", region: "Richmond, VA" },
  "232": { zone: 7, half: "b", region: "Richmond, VA" },
  "233": { zone: 8, half: "a", region: "Norfolk, VA" },
  "234": { zone: 8, half: "a", region: "Virginia Beach, VA" },
  "235": { zone: 8, half: "a", region: "Norfolk, VA" },
  "236": { zone: 8, half: "a", region: "Newport News, VA" },
  "237": { zone: 7, half: "b", region: "Portsmouth, VA" },
  "238": { zone: 7, half: "a", region: "Petersburg, VA" },
  "239": { zone: 7, half: "b", region: "Farmville, VA" },
  "240": { zone: 7, half: "a", region: "Roanoke, VA" },
  "241": { zone: 7, half: "a", region: "Roanoke, VA" },
  "242": { zone: 6, half: "b", region: "Bristol, VA" },
  "243": { zone: 7, half: "a", region: "Pulaski, VA" },
  "244": { zone: 6, half: "b", region: "Staunton, VA" },
  "245": { zone: 7, half: "a", region: "Lynchburg, VA" },
  "246": { zone: 6, half: "b", region: "Bluefield, VA" },
  // Southeast
  "247": { zone: 6, half: "b", region: "Bluefield, WV" },
  "248": { zone: 6, half: "b", region: "Bluefield, WV" },
  "249": { zone: 6, half: "b", region: "Lewisburg, WV" },
  "250": { zone: 6, half: "b", region: "Charleston, WV" },
  "251": { zone: 6, half: "b", region: "Charleston, WV" },
  "252": { zone: 6, half: "b", region: "Charleston, WV" },
  "253": { zone: 6, half: "b", region: "Charleston, WV" },
  "254": { zone: 6, half: "b", region: "Martinsburg, WV" },
  "255": { zone: 6, half: "b", region: "Huntington, WV" },
  "256": { zone: 6, half: "b", region: "Huntington, WV" },
  "257": { zone: 6, half: "b", region: "Huntington, WV" },
  "258": { zone: 6, half: "a", region: "Beckley, WV" },
  "259": { zone: 6, half: "b", region: "Beckley, WV" },
  "260": { zone: 6, half: "b", region: "Wheeling, WV" },
  "261": { zone: 6, half: "a", region: "Parkersburg, WV" },
  "262": { zone: 6, half: "a", region: "Clarksburg, WV" },
  "263": { zone: 6, half: "a", region: "Clarksburg, WV" },
  "264": { zone: 6, half: "a", region: "Elkins, WV" },
  "265": { zone: 6, half: "a", region: "Morgantown, WV" },
  "266": { zone: 6, half: "a", region: "Gassaway, WV" },
  "267": { zone: 6, half: "b", region: "Cumberland, MD" },
  "268": { zone: 6, half: "b", region: "Petersburg, WV" },
  // Carolinas
  "270": { zone: 7, half: "b", region: "Greensboro, NC" },
  "271": { zone: 7, half: "b", region: "Winston-Salem, NC" },
  "272": { zone: 7, half: "b", region: "Greensboro, NC" },
  "273": { zone: 7, half: "b", region: "Greensboro, NC" },
  "274": { zone: 7, half: "b", region: "Greensboro, NC" },
  "275": { zone: 7, half: "b", region: "Raleigh, NC" },
  "276": { zone: 7, half: "b", region: "Raleigh, NC" },
  "277": { zone: 7, half: "b", region: "Durham, NC" },
  "278": { zone: 8, half: "a", region: "Rocky Mount, NC" },
  "279": { zone: 8, half: "a", region: "Elizabeth City, NC" },
  "280": { zone: 7, half: "b", region: "Charlotte, NC" },
  "281": { zone: 7, half: "b", region: "Charlotte, NC" },
  "282": { zone: 7, half: "b", region: "Charlotte, NC" },
  "283": { zone: 7, half: "b", region: "Fayetteville, NC" },
  "284": { zone: 8, half: "a", region: "Wilmington, NC" },
  "285": { zone: 7, half: "b", region: "Kinston, NC" },
  "286": { zone: 7, half: "a", region: "Hickory, NC" },
  "287": { zone: 7, half: "a", region: "Asheville, NC" },
  "288": { zone: 7, half: "a", region: "Asheville, NC" },
  "289": { zone: 7, half: "b", region: "Charlotte, NC" },
  "290": { zone: 8, half: "a", region: "Columbia, SC" },
  "291": { zone: 8, half: "a", region: "Columbia, SC" },
  "292": { zone: 8, half: "a", region: "Columbia, SC" },
  "293": { zone: 8, half: "a", region: "Spartanburg, SC" },
  "294": { zone: 8, half: "a", region: "Charleston, SC" },
  "295": { zone: 8, half: "b", region: "Florence, SC" },
  "296": { zone: 8, half: "a", region: "Greenville, SC" },
  "297": { zone: 8, half: "b", region: "Charlotte, NC" },
  "298": { zone: 8, half: "b", region: "Augusta, GA" },
  "299": { zone: 9, half: "a", region: "Beaufort, SC" },
  // Georgia
  "300": { zone: 8, half: "a", region: "Atlanta, GA" },
  "301": { zone: 8, half: "a", region: "Atlanta, GA" },
  "302": { zone: 8, half: "a", region: "Atlanta, GA" },
  "303": { zone: 8, half: "a", region: "Atlanta, GA" },
  "304": { zone: 7, half: "b", region: "Suwanee, GA" },
  "305": { zone: 7, half: "b", region: "Gainesville, GA" },
  "306": { zone: 8, half: "a", region: "Athens, GA" },
  "307": { zone: 8, half: "a", region: "Dalton, GA" },
  "308": { zone: 8, half: "a", region: "Augusta, GA" },
  "309": { zone: 8, half: "a", region: "Augusta, GA" },
  "310": { zone: 8, half: "b", region: "Macon, GA" },
  "311": { zone: 8, half: "b", region: "Atlanta, GA" },
  "312": { zone: 8, half: "b", region: "Macon, GA" },
  "313": { zone: 8, half: "b", region: "Savannah, GA" },
  "314": { zone: 9, half: "a", region: "Savannah, GA" },
  "315": { zone: 8, half: "b", region: "Waycross, GA" },
  "316": { zone: 8, half: "b", region: "Valdosta, GA" },
  "317": { zone: 8, half: "b", region: "Albany, GA" },
  "318": { zone: 8, half: "b", region: "Columbus, GA" },
  "319": { zone: 8, half: "b", region: "Columbus, GA" },
  // Florida
  "320": { zone: 9, half: "a", region: "Jacksonville, FL" },
  "321": { zone: 9, half: "b", region: "Daytona Beach, FL" },
  "322": { zone: 9, half: "a", region: "Jacksonville, FL" },
  "323": { zone: 9, half: "b", region: "Tallahassee, FL" },
  "324": { zone: 8, half: "b", region: "Panama City, FL" },
  "325": { zone: 8, half: "b", region: "Pensacola, FL" },
  "326": { zone: 9, half: "a", region: "Gainesville, FL" },
  "327": { zone: 9, half: "b", region: "Orlando, FL" },
  "328": { zone: 9, half: "b", region: "Orlando, FL" },
  "329": { zone: 9, half: "b", region: "Melbourne, FL" },
  "330": { zone: 10, half: "b", region: "Miami, FL" },
  "331": { zone: 10, half: "b", region: "Miami, FL" },
  "332": { zone: 10, half: "b", region: "Miami, FL" },
  "333": { zone: 10, half: "b", region: "Fort Lauderdale, FL" },
  "334": { zone: 10, half: "a", region: "West Palm Beach, FL" },
  "335": { zone: 10, half: "a", region: "Tampa, FL" },
  "336": { zone: 10, half: "a", region: "Tampa, FL" },
  "337": { zone: 9, half: "b", region: "St. Petersburg, FL" },
  "338": { zone: 9, half: "b", region: "Lakeland, FL" },
  "339": { zone: 10, half: "a", region: "Fort Myers, FL" },
  "340": { zone: 10, half: "a", region: "Sarasota, FL" },
  "341": { zone: 10, half: "a", region: "Naples, FL" },
  "342": { zone: 9, half: "b", region: "Manasota, FL" },
  "344": { zone: 9, half: "b", region: "Gainesville, FL" },
  "346": { zone: 9, half: "b", region: "Tampa, FL" },
  "347": { zone: 9, half: "b", region: "Orlando, FL" },
  "349": { zone: 10, half: "b", region: "Keys, FL" },
  // Alabama/Mississippi/Tennessee/Kentucky
  "350": { zone: 7, half: "b", region: "Birmingham, AL" },
  "351": { zone: 8, half: "a", region: "Birmingham, AL" },
  "352": { zone: 8, half: "a", region: "Tuscaloosa, AL" },
  "354": { zone: 7, half: "b", region: "Decatur, AL" },
  "355": { zone: 7, half: "b", region: "Decatur, AL" },
  "356": { zone: 7, half: "b", region: "Huntsville, AL" },
  "357": { zone: 7, half: "b", region: "Huntsville, AL" },
  "358": { zone: 7, half: "b", region: "Huntsville, AL" },
  "359": { zone: 8, half: "a", region: "Gadsden, AL" },
  "360": { zone: 8, half: "a", region: "Montgomery, AL" },
  "361": { zone: 8, half: "a", region: "Montgomery, AL" },
  "362": { zone: 8, half: "a", region: "Anniston, AL" },
  "363": { zone: 8, half: "a", region: "Dothan, AL" },
  "364": { zone: 8, half: "b", region: "Evergreen, AL" },
  "365": { zone: 8, half: "b", region: "Mobile, AL" },
  "366": { zone: 8, half: "b", region: "Mobile, AL" },
  "367": { zone: 8, half: "a", region: "Selma, AL" },
  "368": { zone: 8, half: "a", region: "Opelika, AL" },
  "369": { zone: 8, half: "a", region: "Meridian, MS" },
  "370": { zone: 7, half: "a", region: "Nashville, TN" },
  "371": { zone: 7, half: "a", region: "Nashville, TN" },
  "372": { zone: 7, half: "a", region: "Nashville, TN" },
  "373": { zone: 7, half: "a", region: "Chattanooga, TN" },
  "374": { zone: 7, half: "a", region: "Chattanooga, TN" },
  "375": { zone: 7, half: "b", region: "Memphis, TN" },
  "376": { zone: 7, half: "a", region: "Johnson City, TN" },
  "377": { zone: 7, half: "a", region: "Knoxville, TN" },
  "378": { zone: 7, half: "a", region: "Knoxville, TN" },
  "379": { zone: 7, half: "a", region: "Knoxville, TN" },
  "380": { zone: 7, half: "b", region: "Memphis, TN" },
  "381": { zone: 7, half: "b", region: "Memphis, TN" },
  "382": { zone: 7, half: "b", region: "McKenzie, TN" },
  "383": { zone: 7, half: "a", region: "Jackson, TN" },
  "384": { zone: 7, half: "a", region: "Columbia, TN" },
  "385": { zone: 7, half: "a", region: "Cookeville, TN" },
  "386": { zone: 8, half: "a", region: "Jackson, MS" },
  "387": { zone: 8, half: "a", region: "Greenville, MS" },
  "388": { zone: 8, half: "a", region: "Tupelo, MS" },
  "389": { zone: 8, half: "a", region: "Grenada, MS" },
  "390": { zone: 8, half: "a", region: "Jackson, MS" },
  "391": { zone: 8, half: "a", region: "Jackson, MS" },
  "392": { zone: 8, half: "b", region: "Brookhaven, MS" },
  "393": { zone: 8, half: "b", region: "Meridian, MS" },
  "394": { zone: 8, half: "b", region: "Hattiesburg, MS" },
  "395": { zone: 8, half: "b", region: "Gulfport, MS" },
  "396": { zone: 8, half: "a", region: "McComb, MS" },
  "397": { zone: 8, half: "a", region: "Columbus, MS" },
  "400": { zone: 6, half: "b", region: "Louisville, KY" },
  "401": { zone: 6, half: "b", region: "Louisville, KY" },
  "402": { zone: 6, half: "b", region: "Louisville, KY" },
  "403": { zone: 6, half: "b", region: "Lexington, KY" },
  "404": { zone: 6, half: "b", region: "Lexington, KY" },
  "405": { zone: 6, half: "b", region: "Lexington, KY" },
  "406": { zone: 6, half: "b", region: "Frankfort, KY" },
  "407": { zone: 6, half: "b", region: "Corbin, KY" },
  "408": { zone: 6, half: "b", region: "London, KY" },
  "409": { zone: 6, half: "b", region: "London, KY" },
  "410": { zone: 6, half: "b", region: "Cincinnati area, KY" },
  "411": { zone: 6, half: "b", region: "Ashland, KY" },
  "412": { zone: 6, half: "b", region: "Ashland, KY" },
  "413": { zone: 6, half: "a", region: "Campton, KY" },
  "414": { zone: 6, half: "b", region: "Campton, KY" },
  "415": { zone: 6, half: "b", region: "Pikeville, KY" },
  "416": { zone: 6, half: "b", region: "Pikeville, KY" },
  "417": { zone: 6, half: "b", region: "Hazard, KY" },
  "418": { zone: 6, half: "b", region: "Hazard, KY" },
  "420": { zone: 7, half: "a", region: "Paducah, KY" },
  "421": { zone: 7, half: "a", region: "Bowling Green, KY" },
  "422": { zone: 6, half: "b", region: "Owensboro, KY" },
  "423": { zone: 6, half: "b", region: "Owensboro, KY" },
  "424": { zone: 6, half: "b", region: "Henderson, KY" },
  "425": { zone: 6, half: "b", region: "Somerset, KY" },
  "426": { zone: 6, half: "b", region: "Somerset, KY" },
  "427": { zone: 6, half: "b", region: "Elizabethtown, KY" },
  // Ohio/Indiana/Michigan
  "430": { zone: 6, half: "a", region: "Columbus, OH" },
  "431": { zone: 6, half: "a", region: "Columbus, OH" },
  "432": { zone: 6, half: "a", region: "Columbus, OH" },
  "433": { zone: 6, half: "a", region: "Columbus, OH" },
  "434": { zone: 6, half: "a", region: "Toledo, OH" },
  "435": { zone: 6, half: "a", region: "Toledo, OH" },
  "436": { zone: 6, half: "a", region: "Toledo, OH" },
  "437": { zone: 6, half: "a", region: "Zanesville, OH" },
  "438": { zone: 6, half: "a", region: "Zanesville, OH" },
  "439": { zone: 5, half: "b", region: "Steubenville, OH" },
  "440": { zone: 6, half: "b", region: "Cleveland, OH" },
  "441": { zone: 6, half: "a", region: "Cleveland, OH" },
  "442": { zone: 6, half: "a", region: "Akron, OH" },
  "443": { zone: 6, half: "a", region: "Akron, OH" },
  "444": { zone: 6, half: "a", region: "Youngstown, OH" },
  "445": { zone: 6, half: "a", region: "Youngstown, OH" },
  "446": { zone: 6, half: "a", region: "Canton, OH" },
  "447": { zone: 6, half: "a", region: "Canton, OH" },
  "448": { zone: 6, half: "a", region: "Mansfield, OH" },
  "449": { zone: 5, half: "b", region: "Mansfield, OH" },
  "450": { zone: 6, half: "a", region: "Cincinnati, OH" },
  "451": { zone: 6, half: "a", region: "Cincinnati, OH" },
  "452": { zone: 6, half: "b", region: "Cincinnati, OH" },
  "453": { zone: 6, half: "a", region: "Dayton, OH" },
  "454": { zone: 6, half: "a", region: "Dayton, OH" },
  "455": { zone: 6, half: "a", region: "Springfield, OH" },
  "456": { zone: 6, half: "a", region: "Chillicothe, OH" },
  "457": { zone: 6, half: "b", region: "Athens, OH" },
  "458": { zone: 6, half: "a", region: "Lima, OH" },
  "460": { zone: 6, half: "a", region: "Indianapolis, IN" },
  "461": { zone: 6, half: "a", region: "Indianapolis, IN" },
  "462": { zone: 6, half: "a", region: "Indianapolis, IN" },
  "463": { zone: 5, half: "b", region: "South Bend, IN" },
  "464": { zone: 5, half: "b", region: "Gary, IN" },
  "465": { zone: 5, half: "b", region: "South Bend, IN" },
  "466": { zone: 5, half: "b", region: "South Bend, IN" },
  "467": { zone: 5, half: "b", region: "Fort Wayne, IN" },
  "468": { zone: 5, half: "b", region: "Fort Wayne, IN" },
  "469": { zone: 5, half: "b", region: "Kokomo, IN" },
  "470": { zone: 6, half: "a", region: "Cincinnati area, IN" },
  "471": { zone: 6, half: "a", region: "New Albany, IN" },
  "472": { zone: 6, half: "a", region: "Columbus, IN" },
  "473": { zone: 6, half: "a", region: "Muncie, IN" },
  "474": { zone: 6, half: "a", region: "Bloomington, IN" },
  "475": { zone: 6, half: "a", region: "Washington, IN" },
  "476": { zone: 6, half: "b", region: "Evansville, IN" },
  "477": { zone: 6, half: "b", region: "Evansville, IN" },
  "478": { zone: 6, half: "a", region: "Terre Haute, IN" },
  "479": { zone: 5, half: "b", region: "Lafayette, IN" },
  "480": { zone: 6, half: "a", region: "Detroit, MI" },
  "481": { zone: 6, half: "b", region: "Detroit, MI" },
  "482": { zone: 6, half: "b", region: "Detroit, MI" },
  "483": { zone: 6, half: "a", region: "Flint, MI" },
  "484": { zone: 6, half: "a", region: "Flint, MI" },
  "485": { zone: 6, half: "a", region: "Flint, MI" },
  "486": { zone: 6, half: "a", region: "Saginaw, MI" },
  "487": { zone: 5, half: "b", region: "Saginaw, MI" },
  "488": { zone: 6, half: "a", region: "Lansing, MI" },
  "489": { zone: 6, half: "a", region: "Lansing, MI" },
  "490": { zone: 6, half: "a", region: "Kalamazoo, MI" },
  "491": { zone: 6, half: "a", region: "Kalamazoo, MI" },
  "492": { zone: 5, half: "b", region: "Jackson, MI" },
  "493": { zone: 6, half: "a", region: "Grand Rapids, MI" },
  "494": { zone: 6, half: "a", region: "Muskegon, MI" },
  "495": { zone: 5, half: "b", region: "Grand Rapids, MI" },
  "496": { zone: 5, half: "b", region: "Traverse City, MI" },
  "497": { zone: 5, half: "b", region: "Gaylord, MI" },
  "498": { zone: 5, half: "a", region: "Iron Mountain, MI" },
  "499": { zone: 4, half: "b", region: "Iron Mountain, MI" },
  // Midwest
  "500": { zone: 5, half: "b", region: "Des Moines, IA" },
  "501": { zone: 5, half: "b", region: "Des Moines, IA" },
  "502": { zone: 5, half: "b", region: "Des Moines, IA" },
  "503": { zone: 5, half: "b", region: "Des Moines, IA" },
  "504": { zone: 5, half: "a", region: "Mason City, IA" },
  "505": { zone: 5, half: "a", region: "Fort Dodge, IA" },
  "506": { zone: 5, half: "a", region: "Waterloo, IA" },
  "507": { zone: 5, half: "a", region: "Waterloo, IA" },
  "508": { zone: 5, half: "a", region: "Creston, IA" },
  "509": { zone: 5, half: "b", region: "Des Moines, IA" },
  "510": { zone: 5, half: "b", region: "Sioux City, IA" },
  "511": { zone: 5, half: "a", region: "Sioux City, IA" },
  "512": { zone: 5, half: "b", region: "Sioux City, IA" },
  "513": { zone: 5, half: "b", region: "Council Bluffs, IA" },
  "514": { zone: 5, half: "b", region: "Carroll, IA" },
  "515": { zone: 5, half: "b", region: "Omaha, NE area" },
  "516": { zone: 5, half: "a", region: "Shenandoah, IA" },
  "520": { zone: 5, half: "b", region: "Dubuque, IA" },
  "521": { zone: 5, half: "a", region: "Decorah, IA" },
  "522": { zone: 5, half: "b", region: "Cedar Rapids, IA" },
  "523": { zone: 5, half: "b", region: "Cedar Rapids, IA" },
  "524": { zone: 5, half: "b", region: "Cedar Rapids, IA" },
  "525": { zone: 5, half: "b", region: "Ottumwa, IA" },
  "526": { zone: 5, half: "b", region: "Burlington, IA" },
  "527": { zone: 5, half: "b", region: "Rock Island, IL area" },
  "528": { zone: 5, half: "b", region: "Davenport, IA" },
  // Wisconsin/Minnesota/Dakotas
  "530": { zone: 5, half: "b", region: "Madison, WI" },
  "531": { zone: 5, half: "b", region: "Milwaukee, WI" },
  "532": { zone: 5, half: "b", region: "Milwaukee, WI" },
  "534": { zone: 5, half: "a", region: "Racine, WI" },
  "535": { zone: 5, half: "a", region: "Madison, WI" },
  "537": { zone: 5, half: "a", region: "Madison, WI" },
  "538": { zone: 4, half: "b", region: "La Crosse, WI" },
  "539": { zone: 4, half: "b", region: "Portage, WI" },
  "540": { zone: 4, half: "b", region: "Wausau, WI" },
  "541": { zone: 4, half: "a", region: "Green Bay, WI" },
  "542": { zone: 4, half: "b", region: "Green Bay, WI" },
  "543": { zone: 4, half: "b", region: "Green Bay, WI" },
  "544": { zone: 4, half: "b", region: "Wausau, WI" },
  "545": { zone: 4, half: "a", region: "Rhinelander, WI" },
  "546": { zone: 4, half: "a", region: "La Crosse, WI" },
  "547": { zone: 4, half: "b", region: "Eau Claire, WI" },
  "548": { zone: 4, half: "a", region: "Spooner, WI" },
  "549": { zone: 4, half: "a", region: "Oshkosh, WI" },
  "550": { zone: 4, half: "b", region: "St. Paul, MN" },
  "551": { zone: 4, half: "b", region: "St. Paul, MN" },
  "553": { zone: 4, half: "b", region: "Minneapolis, MN" },
  "554": { zone: 4, half: "b", region: "Minneapolis, MN" },
  "556": { zone: 4, half: "a", region: "Duluth, MN" },
  "557": { zone: 4, half: "a", region: "Duluth, MN" },
  "558": { zone: 3, half: "b", region: "Duluth, MN" },
  "559": { zone: 4, half: "a", region: "Rochester, MN" },
  "560": { zone: 4, half: "b", region: "Mankato, MN" },
  "561": { zone: 4, half: "a", region: "Windom, MN" },
  "562": { zone: 4, half: "a", region: "Willmar, MN" },
  "563": { zone: 4, half: "a", region: "St. Cloud, MN" },
  "564": { zone: 3, half: "b", region: "Brainerd, MN" },
  "565": { zone: 3, half: "b", region: "Detroit Lakes, MN" },
  "566": { zone: 3, half: "b", region: "Bemidji, MN" },
  "567": { zone: 3, half: "a", region: "Thief River Falls, MN" },
  "569": { zone: 4, half: "a", region: "Worthington, MN" },
  "570": { zone: 4, half: "b", region: "Sioux Falls, SD" },
  "571": { zone: 4, half: "b", region: "Sioux Falls, SD" },
  "572": { zone: 4, half: "a", region: "Watertown, SD" },
  "573": { zone: 4, half: "a", region: "Mitchell, SD" },
  "574": { zone: 4, half: "a", region: "Aberdeen, SD" },
  "575": { zone: 4, half: "a", region: "Pierre, SD" },
  "576": { zone: 4, half: "a", region: "Mobridge, SD" },
  "577": { zone: 4, half: "a", region: "Rapid City, SD" },
  "580": { zone: 4, half: "a", region: "Fargo, ND" },
  "581": { zone: 4, half: "a", region: "Fargo, ND" },
  "582": { zone: 3, half: "b", region: "Grand Forks, ND" },
  "583": { zone: 3, half: "b", region: "Devils Lake, ND" },
  "584": { zone: 3, half: "b", region: "Jamestown, ND" },
  "585": { zone: 4, half: "a", region: "Bismarck, ND" },
  "586": { zone: 3, half: "b", region: "Dickinson, ND" },
  "587": { zone: 3, half: "b", region: "Minot, ND" },
  "588": { zone: 3, half: "a", region: "Williston, ND" },
  // Illinois
  "600": { zone: 5, half: "b", region: "Chicago, IL" },
  "601": { zone: 5, half: "b", region: "Chicago, IL" },
  "602": { zone: 6, half: "a", region: "Evanston, IL" },
  "603": { zone: 5, half: "b", region: "Oak Park, IL" },
  "604": { zone: 5, half: "b", region: "Chicago S, IL" },
  "605": { zone: 5, half: "b", region: "Chicago SW, IL" },
  "606": { zone: 6, half: "a", region: "Chicago, IL" },
  "607": { zone: 5, half: "b", region: "Chicago W, IL" },
  "608": { zone: 5, half: "b", region: "Chicago NW, IL" },
  "609": { zone: 5, half: "b", region: "Kankakee, IL" },
  "610": { zone: 5, half: "b", region: "Rockford, IL" },
  "611": { zone: 5, half: "b", region: "Rockford, IL" },
  "612": { zone: 5, half: "b", region: "Rock Island, IL" },
  "613": { zone: 5, half: "b", region: "La Salle, IL" },
  "614": { zone: 5, half: "b", region: "Galesburg, IL" },
  "615": { zone: 5, half: "b", region: "Peoria, IL" },
  "616": { zone: 5, half: "b", region: "Peoria, IL" },
  "617": { zone: 5, half: "b", region: "Bloomington, IL" },
  "618": { zone: 5, half: "b", region: "Champaign, IL" },
  "619": { zone: 5, half: "b", region: "Champaign, IL" },
  "620": { zone: 6, half: "a", region: "St. Louis area, IL" },
  "622": { zone: 6, half: "b", region: "St. Louis area, IL" },
  "623": { zone: 6, half: "a", region: "Quincy, IL" },
  "624": { zone: 6, half: "a", region: "Effingham, IL" },
  "625": { zone: 6, half: "a", region: "Springfield, IL" },
  "626": { zone: 6, half: "a", region: "Springfield, IL" },
  "627": { zone: 6, half: "a", region: "Springfield, IL" },
  "628": { zone: 6, half: "b", region: "Centralia, IL" },
  "629": { zone: 6, half: "b", region: "Carbondale, IL" },
  // Missouri/Kansas/Nebraska
  "630": { zone: 6, half: "b", region: "St. Louis, MO" },
  "631": { zone: 6, half: "b", region: "St. Louis, MO" },
  "633": { zone: 6, half: "a", region: "St. Louis, MO" },
  "634": { zone: 6, half: "a", region: "Quincy area, MO" },
  "635": { zone: 6, half: "a", region: "Kirksville, MO" },
  "636": { zone: 6, half: "a", region: "Flat River, MO" },
  "637": { zone: 6, half: "b", region: "Cape Girardeau, MO" },
  "638": { zone: 6, half: "b", region: "Sikeston, MO" },
  "639": { zone: 6, half: "b", region: "Poplar Bluff, MO" },
  "640": { zone: 6, half: "a", region: "Kansas City, MO" },
  "641": { zone: 6, half: "a", region: "Kansas City, MO" },
  "644": { zone: 6, half: "a", region: "St. Joseph, MO" },
  "645": { zone: 6, half: "a", region: "Chillicothe, MO" },
  "646": { zone: 6, half: "a", region: "Chillicothe, MO" },
  "647": { zone: 6, half: "a", region: "Harrisonville, MO" },
  "648": { zone: 6, half: "a", region: "Springfield, MO" },
  "649": { zone: 6, half: "b", region: "Kansas City, MO" },
  "650": { zone: 6, half: "a", region: "Jefferson City, MO" },
  "651": { zone: 6, half: "a", region: "Jefferson City, MO" },
  "652": { zone: 6, half: "a", region: "Columbia, MO" },
  "653": { zone: 6, half: "a", region: "Sedalia, MO" },
  "654": { zone: 6, half: "b", region: "Rolla, MO" },
  "655": { zone: 6, half: "b", region: "Rolla, MO" },
  "656": { zone: 6, half: "b", region: "Springfield, MO" },
  "657": { zone: 6, half: "b", region: "Springfield, MO" },
  "658": { zone: 6, half: "b", region: "Springfield, MO" },
  "659": { zone: 7, half: "a", region: "Joplin, MO" },
  "660": { zone: 6, half: "a", region: "Kansas City, KS" },
  "661": { zone: 6, half: "a", region: "Kansas City, KS" },
  "662": { zone: 6, half: "a", region: "Shawnee Mission, KS" },
  "664": { zone: 6, half: "a", region: "Topeka, KS" },
  "665": { zone: 6, half: "a", region: "Topeka, KS" },
  "666": { zone: 6, half: "a", region: "Topeka, KS" },
  "667": { zone: 5, half: "b", region: "Fort Scott, KS" },
  "668": { zone: 6, half: "a", region: "Emporia, KS" },
  "669": { zone: 6, half: "a", region: "Belleville, KS" },
  "670": { zone: 6, half: "a", region: "Wichita, KS" },
  "671": { zone: 6, half: "b", region: "Wichita, KS" },
  "672": { zone: 6, half: "a", region: "Independence, KS" },
  "673": { zone: 6, half: "a", region: "Independence, KS" },
  "674": { zone: 6, half: "a", region: "Salina, KS" },
  "675": { zone: 6, half: "a", region: "Hutchinson, KS" },
  "676": { zone: 6, half: "a", region: "Hays, KS" },
  "677": { zone: 6, half: "a", region: "Colby, KS" },
  "678": { zone: 6, half: "a", region: "Dodge City, KS" },
  "679": { zone: 6, half: "b", region: "Liberal, KS" },
  "680": { zone: 5, half: "b", region: "Omaha, NE" },
  "681": { zone: 5, half: "b", region: "Omaha, NE" },
  "683": { zone: 5, half: "b", region: "Lincoln, NE" },
  "684": { zone: 5, half: "b", region: "Lincoln, NE" },
  "685": { zone: 5, half: "b", region: "Lincoln, NE" },
  "686": { zone: 5, half: "a", region: "Columbus, NE" },
  "687": { zone: 5, half: "a", region: "Norfolk, NE" },
  "688": { zone: 5, half: "a", region: "Grand Island, NE" },
  "689": { zone: 5, half: "a", region: "Hastings, NE" },
  "690": { zone: 5, half: "a", region: "McCook, NE" },
  "691": { zone: 5, half: "a", region: "North Platte, NE" },
  "692": { zone: 5, half: "a", region: "Valentine, NE" },
  "693": { zone: 4, half: "b", region: "Alliance, NE" },
  // Louisiana/Arkansas
  "700": { zone: 9, half: "a", region: "New Orleans, LA" },
  "701": { zone: 9, half: "a", region: "New Orleans, LA" },
  "703": { zone: 9, half: "a", region: "Thibodaux, LA" },
  "704": { zone: 9, half: "a", region: "Hammond, LA" },
  "705": { zone: 8, half: "b", region: "Lafayette, LA" },
  "706": { zone: 8, half: "b", region: "Lake Charles, LA" },
  "707": { zone: 8, half: "b", region: "Baton Rouge, LA" },
  "708": { zone: 8, half: "b", region: "Baton Rouge, LA" },
  "710": { zone: 8, half: "b", region: "Shreveport, LA" },
  "711": { zone: 8, half: "b", region: "Shreveport, LA" },
  "712": { zone: 8, half: "a", region: "Monroe, LA" },
  "713": { zone: 8, half: "b", region: "Alexandria, LA" },
  "714": { zone: 8, half: "b", region: "Alexandria, LA" },
  "716": { zone: 8, half: "a", region: "Pine Bluff, AR" },
  "717": { zone: 7, half: "b", region: "Camden, AR" },
  "718": { zone: 7, half: "b", region: "Texarkana, AR" },
  "719": { zone: 8, half: "a", region: "Hot Springs, AR" },
  "720": { zone: 7, half: "b", region: "Little Rock, AR" },
  "721": { zone: 7, half: "b", region: "Little Rock, AR" },
  "722": { zone: 7, half: "b", region: "Little Rock, AR" },
  "723": { zone: 7, half: "a", region: "West Memphis, AR" },
  "724": { zone: 7, half: "a", region: "Jonesboro, AR" },
  "725": { zone: 7, half: "a", region: "Batesville, AR" },
  "726": { zone: 7, half: "a", region: "Harrison, AR" },
  "727": { zone: 7, half: "a", region: "Fayetteville, AR" },
  "728": { zone: 6, half: "b", region: "Russellville, AR" },
  "729": { zone: 7, half: "a", region: "Fort Smith, AR" },
  // Texas
  "730": { zone: 7, half: "b", region: "Dallas, TX" },
  "731": { zone: 8, half: "a", region: "Dallas, TX" },
  "733": { zone: 8, half: "a", region: "Fort Worth, TX" },
  "734": { zone: 8, half: "a", region: "Dallas, TX" },
  "735": { zone: 8, half: "a", region: "Dallas, TX" },
  "736": { zone: 8, half: "a", region: "Dallas, TX" },
  "737": { zone: 8, half: "b", region: "Austin, TX" },
  "738": { zone: 8, half: "b", region: "Austin, TX" },
  "739": { zone: 7, half: "b", region: "Beaumont, TX" },
  "740": { zone: 7, half: "b", region: "Texarkana, TX" },
  "741": { zone: 8, half: "a", region: "Sherman, TX" },
  "743": { zone: 8, half: "a", region: "Wichita Falls, TX" },
  "744": { zone: 7, half: "b", region: "Wichita Falls, TX" },
  "745": { zone: 8, half: "a", region: "Dallas, TX" },
  "746": { zone: 8, half: "a", region: "Greenville, TX" },
  "747": { zone: 8, half: "a", region: "Waco, TX" },
  "748": { zone: 8, half: "a", region: "Waco, TX" },
  "749": { zone: 7, half: "b", region: "Waco, TX" },
  "750": { zone: 8, half: "a", region: "Dallas, TX" },
  "751": { zone: 8, half: "a", region: "Dallas, TX" },
  "752": { zone: 8, half: "a", region: "Dallas, TX" },
  "753": { zone: 8, half: "a", region: "Dallas, TX" },
  "754": { zone: 8, half: "a", region: "Greenville, TX" },
  "755": { zone: 8, half: "a", region: "Texarkana, TX" },
  "756": { zone: 8, half: "a", region: "Longview, TX" },
  "757": { zone: 8, half: "b", region: "Tyler, TX" },
  "758": { zone: 8, half: "a", region: "Palestine, TX" },
  "759": { zone: 8, half: "a", region: "Lufkin, TX" },
  "760": { zone: 8, half: "a", region: "Fort Worth, TX" },
  "761": { zone: 8, half: "a", region: "Fort Worth, TX" },
  "762": { zone: 8, half: "a", region: "Fort Worth, TX" },
  "763": { zone: 8, half: "a", region: "Wichita Falls, TX" },
  "764": { zone: 7, half: "b", region: "Stephenville, TX" },
  "765": { zone: 8, half: "a", region: "Waco, TX" },
  "766": { zone: 8, half: "a", region: "Waco, TX" },
  "767": { zone: 8, half: "a", region: "Waco, TX" },
  "768": { zone: 7, half: "b", region: "Abilene, TX" },
  "769": { zone: 8, half: "a", region: "Midland, TX" },
  "770": { zone: 9, half: "a", region: "Houston, TX" },
  "771": { zone: 9, half: "a", region: "Houston, TX" },
  "772": { zone: 9, half: "a", region: "Houston, TX" },
  "773": { zone: 9, half: "a", region: "Huntsville, TX" },
  "774": { zone: 9, half: "a", region: "Wharton, TX" },
  "775": { zone: 9, half: "a", region: "Galveston, TX" },
  "776": { zone: 9, half: "a", region: "Beaumont, TX" },
  "777": { zone: 9, half: "a", region: "Beaumont, TX" },
  "778": { zone: 8, half: "b", region: "Bryan, TX" },
  "779": { zone: 8, half: "b", region: "Victoria, TX" },
  "780": { zone: 8, half: "b", region: "San Antonio, TX" },
  "781": { zone: 8, half: "b", region: "San Antonio, TX" },
  "782": { zone: 8, half: "b", region: "San Antonio, TX" },
  "783": { zone: 9, half: "a", region: "Corpus Christi, TX" },
  "784": { zone: 9, half: "a", region: "Corpus Christi, TX" },
  "785": { zone: 9, half: "b", region: "McAllen, TX" },
  "786": { zone: 8, half: "b", region: "Austin, TX" },
  "787": { zone: 8, half: "b", region: "Austin, TX" },
  "788": { zone: 8, half: "b", region: "San Antonio, TX" },
  "789": { zone: 8, half: "b", region: "Austin, TX" },
  "790": { zone: 7, half: "a", region: "Amarillo, TX" },
  "791": { zone: 7, half: "a", region: "Amarillo, TX" },
  "792": { zone: 7, half: "b", region: "Childress, TX" },
  "793": { zone: 7, half: "b", region: "Lubbock, TX" },
  "794": { zone: 7, half: "b", region: "Lubbock, TX" },
  "795": { zone: 7, half: "b", region: "Abilene, TX" },
  "796": { zone: 7, half: "b", region: "Abilene, TX" },
  "797": { zone: 7, half: "b", region: "Midland, TX" },
  "798": { zone: 8, half: "a", region: "El Paso, TX" },
  "799": { zone: 8, half: "a", region: "El Paso, TX" },
  // Mountain/West
  "800": { zone: 5, half: "b", region: "Denver, CO" },
  "801": { zone: 5, half: "b", region: "Denver, CO" },
  "802": { zone: 6, half: "a", region: "Denver, CO" },
  "803": { zone: 5, half: "b", region: "Boulder, CO" },
  "804": { zone: 5, half: "b", region: "Denver, CO" },
  "805": { zone: 5, half: "b", region: "Longmont, CO" },
  "806": { zone: 5, half: "b", region: "Denver, CO" },
  "807": { zone: 5, half: "b", region: "Denver, CO" },
  "808": { zone: 5, half: "a", region: "Colorado Springs, CO" },
  "809": { zone: 5, half: "a", region: "Colorado Springs, CO" },
  "810": { zone: 5, half: "a", region: "Pueblo, CO" },
  "811": { zone: 5, half: "a", region: "Alamosa, CO" },
  "812": { zone: 5, half: "b", region: "Salida, CO" },
  "813": { zone: 5, half: "b", region: "Durango, CO" },
  "814": { zone: 5, half: "a", region: "Grand Junction, CO" },
  "815": { zone: 5, half: "a", region: "Grand Junction, CO" },
  "816": { zone: 5, half: "a", region: "Glenwood Springs, CO" },
  "820": { zone: 5, half: "a", region: "Cheyenne, WY" },
  "821": { zone: 5, half: "a", region: "Yellowstone, WY" },
  "822": { zone: 4, half: "b", region: "Wheatland, WY" },
  "823": { zone: 4, half: "b", region: "Rawlins, WY" },
  "824": { zone: 4, half: "a", region: "Worland, WY" },
  "825": { zone: 4, half: "b", region: "Riverton, WY" },
  "826": { zone: 4, half: "b", region: "Casper, WY" },
  "827": { zone: 4, half: "a", region: "Gillette, WY" },
  "828": { zone: 4, half: "a", region: "Sheridan, WY" },
  "829": { zone: 5, half: "a", region: "Rock Springs, WY" },
  "830": { zone: 5, half: "a", region: "Rock Springs, WY" },
  "831": { zone: 5, half: "a", region: "Rock Springs, WY" },
  "832": { zone: 4, half: "b", region: "Pocatello, ID" },
  "833": { zone: 5, half: "a", region: "Twin Falls, ID" },
  "834": { zone: 5, half: "a", region: "Pocatello, ID" },
  "835": { zone: 6, half: "b", region: "Lewiston, ID" },
  "836": { zone: 6, half: "a", region: "Boise, ID" },
  "837": { zone: 6, half: "b", region: "Boise, ID" },
  "838": { zone: 5, half: "a", region: "Spokane area, ID" },
  "840": { zone: 7, half: "a", region: "Salt Lake City, UT" },
  "841": { zone: 7, half: "a", region: "Salt Lake City, UT" },
  "843": { zone: 6, half: "a", region: "Logan, UT" },
  "844": { zone: 6, half: "b", region: "Ogden, UT" },
  "845": { zone: 6, half: "a", region: "Provo, UT" },
  "846": { zone: 6, half: "a", region: "Provo, UT" },
  "847": { zone: 5, half: "b", region: "Price, UT" },
  // Montana
  "590": { zone: 4, half: "b", region: "Billings, MT" },
  "591": { zone: 4, half: "b", region: "Billings, MT" },
  "592": { zone: 4, half: "b", region: "Wolf Point, MT" },
  "593": { zone: 4, half: "a", region: "Miles City, MT" },
  "594": { zone: 4, half: "b", region: "Great Falls, MT" },
  "595": { zone: 4, half: "a", region: "Havre, MT" },
  "596": { zone: 4, half: "b", region: "Helena, MT" },
  "597": { zone: 4, half: "a", region: "Butte, MT" },
  "598": { zone: 4, half: "b", region: "Missoula, MT" },
  "599": { zone: 5, half: "a", region: "Kalispell, MT" },
  // Southwest
  "850": { zone: 9, half: "b", region: "Phoenix, AZ" },
  "851": { zone: 9, half: "b", region: "Phoenix, AZ" },
  "852": { zone: 9, half: "b", region: "Mesa, AZ" },
  "853": { zone: 9, half: "b", region: "Phoenix, AZ" },
  "855": { zone: 8, half: "a", region: "Globe, AZ" },
  "856": { zone: 9, half: "a", region: "Tucson, AZ" },
  "857": { zone: 9, half: "a", region: "Tucson, AZ" },
  "859": { zone: 6, half: "b", region: "Show Low, AZ" },
  "860": { zone: 8, half: "a", region: "Flagstaff, AZ" },
  "863": { zone: 8, half: "a", region: "Prescott, AZ" },
  "864": { zone: 7, half: "a", region: "Kingman, AZ" },
  "865": { zone: 9, half: "a", region: "Yuma, AZ" },
  "870": { zone: 7, half: "a", region: "Albuquerque, NM" },
  "871": { zone: 7, half: "a", region: "Albuquerque, NM" },
  "873": { zone: 6, half: "b", region: "Gallup, NM" },
  "874": { zone: 6, half: "a", region: "Farmington, NM" },
  "875": { zone: 7, half: "a", region: "Santa Fe, NM" },
  "877": { zone: 6, half: "b", region: "Las Vegas, NM" },
  "878": { zone: 7, half: "a", region: "Socorro, NM" },
  "879": { zone: 7, half: "b", region: "Truth or Consequences, NM" },
  "880": { zone: 8, half: "a", region: "Las Cruces, NM" },
  "881": { zone: 7, half: "b", region: "Clovis, NM" },
  "882": { zone: 7, half: "a", region: "Roswell, NM" },
  "883": { zone: 7, half: "b", region: "Alamogordo, NM" },
  "884": { zone: 7, half: "a", region: "Tucumcari, NM" },
  "885": { zone: 8, half: "a", region: "El Paso area, NM" },
  "889": { zone: 9, half: "a", region: "Las Vegas, NV" },
  "890": { zone: 9, half: "a", region: "Las Vegas, NV" },
  "891": { zone: 9, half: "a", region: "Las Vegas, NV" },
  "893": { zone: 7, half: "a", region: "Ely, NV" },
  "894": { zone: 7, half: "a", region: "Reno, NV" },
  "895": { zone: 7, half: "a", region: "Reno, NV" },
  "897": { zone: 6, half: "b", region: "Carson City, NV" },
  "898": { zone: 6, half: "b", region: "Elko, NV" },
  // West Coast
  "900": { zone: 10, half: "b", region: "Los Angeles, CA" },
  "901": { zone: 10, half: "b", region: "Los Angeles, CA" },
  "902": { zone: 10, half: "b", region: "Inglewood, CA" },
  "903": { zone: 10, half: "a", region: "Inglewood, CA" },
  "904": { zone: 10, half: "a", region: "Santa Monica, CA" },
  "905": { zone: 10, half: "a", region: "Torrance, CA" },
  "906": { zone: 10, half: "a", region: "Whittier, CA" },
  "907": { zone: 10, half: "a", region: "Long Beach, CA" },
  "908": { zone: 10, half: "a", region: "Long Beach, CA" },
  "910": { zone: 10, half: "a", region: "Pasadena, CA" },
  "911": { zone: 10, half: "a", region: "Pasadena, CA" },
  "912": { zone: 10, half: "a", region: "Glendale, CA" },
  "913": { zone: 9, half: "b", region: "Van Nuys, CA" },
  "914": { zone: 9, half: "b", region: "Van Nuys, CA" },
  "915": { zone: 10, half: "a", region: "Burbank, CA" },
  "916": { zone: 9, half: "b", region: "North Hollywood, CA" },
  "917": { zone: 10, half: "a", region: "Industry, CA" },
  "918": { zone: 9, half: "b", region: "Alhambra, CA" },
  "919": { zone: 9, half: "b", region: "San Diego, CA" },
  "920": { zone: 10, half: "a", region: "San Diego, CA" },
  "921": { zone: 10, half: "a", region: "San Diego, CA" },
  "922": { zone: 9, half: "b", region: "Palm Springs, CA" },
  "923": { zone: 9, half: "b", region: "San Bernardino, CA" },
  "924": { zone: 9, half: "b", region: "San Bernardino, CA" },
  "925": { zone: 9, half: "b", region: "Riverside, CA" },
  "926": { zone: 10, half: "a", region: "Santa Ana, CA" },
  "927": { zone: 10, half: "a", region: "Santa Ana, CA" },
  "928": { zone: 9, half: "b", region: "Anaheim, CA" },
  "930": { zone: 9, half: "b", region: "Oxnard, CA" },
  "931": { zone: 10, half: "a", region: "Santa Barbara, CA" },
  "932": { zone: 9, half: "b", region: "Bakersfield, CA" },
  "933": { zone: 9, half: "a", region: "Bakersfield, CA" },
  "934": { zone: 9, half: "b", region: "San Luis Obispo, CA" },
  "935": { zone: 9, half: "a", region: "Mojave, CA" },
  "936": { zone: 9, half: "b", region: "Fresno, CA" },
  "937": { zone: 9, half: "b", region: "Fresno, CA" },
  "938": { zone: 9, half: "a", region: "Fresno, CA" },
  "939": { zone: 9, half: "b", region: "Salinas, CA" },
  "940": { zone: 10, half: "a", region: "San Francisco, CA" },
  "941": { zone: 10, half: "a", region: "San Francisco, CA" },
  "942": { zone: 10, half: "a", region: "Sacramento, CA" },
  "943": { zone: 9, half: "b", region: "Palo Alto, CA" },
  "944": { zone: 10, half: "a", region: "San Mateo, CA" },
  "945": { zone: 9, half: "b", region: "Oakland, CA" },
  "946": { zone: 9, half: "b", region: "Oakland, CA" },
  "947": { zone: 10, half: "a", region: "Berkeley, CA" },
  "948": { zone: 9, half: "b", region: "Richmond, CA" },
  "949": { zone: 9, half: "b", region: "San Rafael, CA" },
  "950": { zone: 9, half: "b", region: "San Jose, CA" },
  "951": { zone: 9, half: "b", region: "San Jose, CA" },
  "952": { zone: 9, half: "b", region: "Stockton, CA" },
  "953": { zone: 9, half: "b", region: "Stockton, CA" },
  "954": { zone: 9, half: "b", region: "Santa Rosa, CA" },
  "955": { zone: 9, half: "b", region: "Eureka, CA" },
  "956": { zone: 9, half: "b", region: "Sacramento, CA" },
  "957": { zone: 9, half: "b", region: "Sacramento, CA" },
  "958": { zone: 9, half: "b", region: "Sacramento, CA" },
  "959": { zone: 9, half: "a", region: "Marysville, CA" },
  "960": { zone: 8, half: "b", region: "Redding, CA" },
  "961": { zone: 8, half: "b", region: "Redding, CA" },
  // Oregon
  "970": { zone: 8, half: "b", region: "Portland, OR" },
  "971": { zone: 8, half: "b", region: "Portland, OR" },
  "972": { zone: 8, half: "b", region: "Portland, OR" },
  "973": { zone: 8, half: "b", region: "Salem, OR" },
  "974": { zone: 8, half: "b", region: "Eugene, OR" },
  "975": { zone: 8, half: "a", region: "Medford, OR" },
  "976": { zone: 7, half: "a", region: "Klamath Falls, OR" },
  "977": { zone: 6, half: "b", region: "Bend, OR" },
  "978": { zone: 6, half: "a", region: "Pendleton, OR" },
  "979": { zone: 6, half: "b", region: "Boise area, OR" },
  // Washington
  "980": { zone: 8, half: "b", region: "Seattle, WA" },
  "981": { zone: 8, half: "b", region: "Seattle, WA" },
  "982": { zone: 8, half: "b", region: "Everett, WA" },
  "983": { zone: 8, half: "b", region: "Tacoma, WA" },
  "984": { zone: 8, half: "b", region: "Tacoma, WA" },
  "985": { zone: 8, half: "b", region: "Olympia, WA" },
  "986": { zone: 8, half: "a", region: "Portland area, WA" },
  "988": { zone: 6, half: "b", region: "Wenatchee, WA" },
  "989": { zone: 6, half: "a", region: "Yakima, WA" },
  "990": { zone: 6, half: "b", region: "Spokane, WA" },
  "991": { zone: 6, half: "b", region: "Spokane, WA" },
  "992": { zone: 6, half: "a", region: "Spokane, WA" },
  "993": { zone: 6, half: "a", region: "Pasco, WA" },
  "994": { zone: 7, half: "a", region: "Clarkston, WA" },
  // Hawaii/Alaska
  "967": { zone: 10, half: "b", region: "Hawaii" },
  "968": { zone: 10, half: "b", region: "Hawaii" },
  "995": { zone: 4, half: "a", region: "Anchorage, AK" },
  "996": { zone: 4, half: "a", region: "Anchorage, AK" },
  "997": { zone: 3, half: "b", region: "Fairbanks, AK" },
  "998": { zone: 4, half: "a", region: "Juneau, AK" },
  "999": { zone: 7, half: "a", region: "Ketchikan, AK" },
};

export function lookupZone(zip: string): { zone: number; half: string; region: string } | null {
  const prefix = zip.replace(/\D/g, "").substring(0, 3);
  if (prefix.length < 3) return null;
  return ZIP3_TO_ZONE[prefix] || null;
}
